server:
  port: ${PORT:0}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: resourcesModule
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/api/resources/**
        - id: songsModule
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/api/songs/**
        - id: storagesModule
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/api/storages/**
        - id: kibanaModule
          uri: ${KIBANA_URL}
          predicates:
            - Path=/kibana/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
