server:
  port: ${PORT:0}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: resource-service
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/api/resources/**
        - id: song-service
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/api/songs/**
        - id: storage-service
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/api/storages/**
        - id: kibana
          uri: ${KIBANA_URL}
          predicates:
            - Path=/kibana/**
  security:
    user:
      password: admin
      roles:
        - ADMIN
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
