server:
  port: ${PORT:5000}
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: resource-processor
  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
  web:
    locale: en
    resources:
      add-mappings: false
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:dev}
  jmx:
    enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  output:
    ansi:
      enabled: detect

configuration:
  aws:
    url: ${AWS_URL}
    region: ${AWS_DEFAULT_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    sqs:
      queue: ${AWS_SQS_QUEUE_NAME}
  resource-service-url: ${RESOURCE_SERVICE_URL}
  song-service-url: ${SONG_SERVICE_URL}
