server:
  port: ${PORT:5000}
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: resource-processor
  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
  web:
    locale: en
    resources:
      add-mappings: false
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:dev}
  jmx:
    enabled: false
  jms:
    template:
      default-destination: ${configuration.aws.sqs.queue}
    listener:
      acknowledge-mode: CLIENT
      concurrency: 3
      max-concurrency: 10
  mvc:
    throw-exception-if-no-handler-found: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  output:
    ansi:
      enabled: detect

resilience4j:
  retry:
    instances:
      fetch-resource-binary-data:
        max-attempts: 3
        wait-duration: 10s
        ignore-exceptions:
          - java.lang.NullPointerException
      create-song-metadata:
        max-attempts: 5
        wait-duration: 2s
      delete-songs-metadata:
        max-attempts: 3
        wait-duration: 5s

configuration:
  aws:
    url: ${AWS_URL}
    region: ${AWS_DEFAULT_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    sqs:
      queue: ${AWS_SQS_QUEUE_NAME}
  resource-service-url: ${RESOURCE_SERVICE_URL}
  song-service-url: ${SONG_SERVICE_URL}
